# Generated by Django 6.0 on 2025-12-09 09:42

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeroImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='About Section Images & Text', editable=False, max_length=50, unique=True)),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='images/about_hero/', verbose_name='Main Image (about_h1l1)')),
                ('image_overlay', models.ImageField(blank=True, null=True, upload_to='images/about_hero/', verbose_name='Overlay Image (about_h1l2)')),
                ('tagline', models.CharField(default='ABOUT US', max_length=100, verbose_name='H5 Tagline (e.g., ABOUT US)')),
                ('title', models.CharField(help_text='Use <br> for line breaks.', max_length=255, verbose_name='H1 Title (e.g., Creative solutions...)')),
                ('content', models.TextField(help_text='The main description paragraph.', verbose_name='Paragraph Content')),
                ('button_text', models.CharField(default='CONTINUE READING', max_length=50, verbose_name='Button Text')),
            ],
            options={
                'verbose_name': 'About Section Image & Text',
                'verbose_name_plural': 'About Section Image & Text',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text="Check this for the first slide to be 'active'.")),
                ('headline', models.CharField(max_length=255, verbose_name='H1 Headline')),
                ('description', models.TextField(verbose_name='Paragraph Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/carousel/', verbose_name='Slide Image (1920x800 recommended)')),
                ('button_text', models.CharField(default='VISIT SHOWROOM', max_length=50)),
                ('button_link', models.URLField(default='#')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'verbose_name_plural': 'Carousel Slides',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Project Title (e.g., Kitchen project 01)')),
                ('image', models.ImageField(upload_to='images/projects/', verbose_name='Project Image')),
                ('categories', models.CharField(help_text='Enter categories separated by commas (e.g., Modern, Coastal, Top Sellers)', max_length=255)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSectionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Project Section Header', editable=False, max_length=50, unique=True)),
                ('tagline', models.CharField(default='OUR PROJECT', max_length=100, verbose_name='H6 Tagline (e.g., OUR PROJECT)')),
                ('title', models.CharField(default='Explore our kitchen designs', max_length=255, verbose_name='H1 Title')),
                ('content', models.TextField(help_text='The main description paragraph. Use <br> for line breaks.', verbose_name='Paragraph Content')),
            ],
            options={
                'verbose_name': 'Project Section Header Text',
                'verbose_name_plural': 'Project Section Header Text',
            },
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('about_short', models.TextField(blank=True, null=True)),
                ('about_long', models.TextField(blank=True, null=True)),
                ('honors', models.TextField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('skill_1_name', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_1_value', models.IntegerField(blank=True, null=True)),
                ('skill_2_name', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_2_value', models.IntegerField(blank=True, null=True)),
                ('skill_3_name', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_3_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamSectionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Team Section Header', editable=False, max_length=50, unique=True)),
                ('tagline', models.CharField(default='MEET OUR TEAM', max_length=100, verbose_name='H6 Tagline (e.g., MEET OUR TEAM)')),
                ('title', models.CharField(default='Creative minds always <br> think someting', help_text='Use <br> for line breaks.', max_length=255, verbose_name='H1 Title')),
            ],
            options={
                'verbose_name': 'Team Section Header Text',
                'verbose_name_plural': 'Team Section Header Text',
            },
        ),
        migrations.CreateModel(
            name='TestimonialClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100, verbose_name='Client Role/Designation')),
                ('quote', models.TextField()),
                ('image', models.ImageField(upload_to='images/testimonials/', verbose_name='Client Image (e.g. 100x100 recommended)')),
                ('slide_group', models.IntegerField(default=1, help_text='Group number for the carousel slide (e.g., 1 for slide 1, 2 for slide 2, etc.)')),
                ('order_in_group', models.IntegerField(default=1, help_text='Position within the slide group (1, 2, or 3)')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['slide_group', 'order_in_group'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='A unique, URL-friendly version of the title.', unique=True)),
                ('image', models.ImageField(upload_to='images/blog/', verbose_name='Blog Post Image')),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Full Blog Content')),
                ('summary', models.TextField(help_text='A brief summary for the homepage card.', max_length=300)),
                ('comment_count', models.IntegerField(default=0)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, to='accounts.blogtag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('productDescript', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('availability', models.CharField(max_length=200, null=True)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='images/Products/')),
                ('rating', models.FloatField(default=0)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('categoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('Information', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('Reviews', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('productID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
            ],
        ),
    ]
