# Generated by Django 6.0 on 2025-12-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text="Check this for the first slide to be 'active'.")),
                ('headline', models.CharField(max_length=255, verbose_name='H1 Headline')),
                ('description', models.TextField(verbose_name='Paragraph Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/carousel/', verbose_name='Slide Image (1920x800 recommended)')),
                ('button_text', models.CharField(default='VISIT SHOWROOM', max_length=50)),
                ('button_link', models.URLField(default='#')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'verbose_name_plural': 'Carousel Slides',
                'ordering': ['order', '-id'],
            },
        ),
    ]
