# Generated by Django 6.0 on 2025-12-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_carouselslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeroImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='About Section Images', editable=False, max_length=50, unique=True)),
                ('image_main', models.ImageField(blank=True, help_text='Corresponds to img/6.jpg', null=True, upload_to='images/about_hero/', verbose_name='Main Image (about_h1l1)')),
                ('image_overlay', models.ImageField(blank=True, help_text='Corresponds to img/7.jpg', null=True, upload_to='images/about_hero/', verbose_name='Overlay Image (about_h1l2)')),
            ],
            options={
                'verbose_name': 'About Section Image Pair',
                'verbose_name_plural': 'About Section Image Pair',
            },
        ),
    ]
