# Generated by Django 6.0 on 2025-12-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('ABA', 'ABA Bank'), ('ACLEDA', 'Acleda Bank')], max_length=20, unique=True)),
                ('qr_image', models.ImageField(upload_to='bank_qr_codes/')),
            ],
        ),
    ]
