# Generated by Django 6.0 on 2025-12-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_aboutheroimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutheroimages',
            options={'verbose_name': 'About Section Image & Text', 'verbose_name_plural': 'About Section Image & Text'},
        ),
        migrations.AddField(
            model_name='aboutheroimages',
            name='button_text',
            field=models.CharField(default='CONTINUE READING', max_length=50, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='aboutheroimages',
            name='content',
            field=models.TextField(default='Default Content', help_text='The main description paragraph.', verbose_name='Paragraph Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutheroimages',
            name='tagline',
            field=models.CharField(default='ABOUT US', max_length=100, verbose_name='H5 Tagline (e.g., ABOUT US)'),
        ),
        migrations.AddField(
            model_name='aboutheroimages',
            name='title',
            field=models.CharField(default='Default Title', help_text='Use <br> for line breaks.', max_length=255, verbose_name='H1 Title (e.g., Creative solutions...)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutheroimages',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='images/about_hero/', verbose_name='Main Image (about_h1l1)'),
        ),
        migrations.AlterField(
            model_name='aboutheroimages',
            name='image_overlay',
            field=models.ImageField(blank=True, null=True, upload_to='images/about_hero/', verbose_name='Overlay Image (about_h1l2)'),
        ),
        migrations.AlterField(
            model_name='aboutheroimages',
            name='name',
            field=models.CharField(default='About Section Images & Text', editable=False, max_length=50, unique=True),
        ),
    ]
