# Generated by Django 6.0 on 2025-12-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_aboutheroimages_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Project Title (e.g., Kitchen project 01)')),
                ('image', models.ImageField(upload_to='images/projects/', verbose_name='Project Image')),
                ('categories', models.CharField(help_text='Enter categories separated by commas (e.g., Modern, Coastal, Top Sellers)', max_length=255)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSectionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Project Section Header', editable=False, max_length=50, unique=True)),
                ('tagline', models.CharField(default='OUR PROJECT', max_length=100, verbose_name='H6 Tagline (e.g., OUR PROJECT)')),
                ('title', models.CharField(default='Explore our kitchen designs', max_length=255, verbose_name='H1 Title')),
                ('content', models.TextField(help_text='The main description paragraph. Use <br> for line breaks.', verbose_name='Paragraph Content')),
            ],
            options={
                'verbose_name': 'Project Section Header Text',
                'verbose_name_plural': 'Project Section Header Text',
            },
        ),
    ]
