# Generated by Django 6.0 on 2025-12-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bankqr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankqr',
            options={'verbose_name': 'Bank QR Code', 'verbose_name_plural': 'Bank QR Codes'},
        ),
        migrations.RemoveField(
            model_name='bankqr',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bankqr',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='bankqr',
            name='bank_code',
            field=models.CharField(default='TEMP_BANK_CODE', max_length=50, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankqr',
            name='qr_code_image',
            field=models.ImageField(default='TEMP_BANK_CODE', upload_to='bank_qrs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankqr',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
    ]
