# Generated by Django 6.0 on 2025-12-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_project_projectsectionheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Member Name')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation (Role, e.g., Designer, Architect)')),
                ('image', models.ImageField(upload_to='images/team_members/', verbose_name='Member Image')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TeamSectionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Team Section Header', editable=False, max_length=50, unique=True)),
                ('tagline', models.CharField(default='MEET OUR TEAM', max_length=100, verbose_name='H6 Tagline (e.g., MEET OUR TEAM)')),
                ('title', models.CharField(default='Creative minds always <br> think someting', help_text='Use <br> for line breaks.', max_length=255, verbose_name='H1 Title')),
            ],
            options={
                'verbose_name': 'Team Section Header Text',
                'verbose_name_plural': 'Team Section Header Text',
            },
        ),
    ]
