# Generated by Django 6.0 on 2025-12-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_bankqr_options_remove_bankqr_id_and_more'),
        ('accounts', '0005_qrcode_name_alter_aboutheroimages_id_and_more'),
    ]

    operations = [
    ]
