# Generated by Django 6.0 on 2025-12-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20251216_0817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankQR',
        ),
    ]
