# Generated by Django 6.0 on 2025-12-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_teammember_teamsectionheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('about_short', models.TextField(blank=True, null=True)),
                ('about_long', models.TextField(blank=True, null=True)),
                ('honors', models.TextField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('skill_1_name', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_1_value', models.IntegerField(blank=True, null=True)),
                ('skill_2_name', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_2_value', models.IntegerField(blank=True, null=True)),
                ('skill_3_name', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_3_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
