# Generated by Django 6.0 on 2025-12-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_teammembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100, verbose_name='Client Role/Designation')),
                ('quote', models.TextField()),
                ('image', models.ImageField(upload_to='images/testimonials/', verbose_name='Client Image (e.g. 100x100 recommended)')),
                ('slide_group', models.IntegerField(default=1, help_text='Group number for the carousel slide (e.g., 1 for slide 1, 2 for slide 2, etc.)')),
                ('order_in_group', models.IntegerField(default=1, help_text='Position within the slide group (1, 2, or 3)')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['slide_group', 'order_in_group'],
            },
        ),
    ]
