# Generated by Django 6.0 on 2025-12-08 17:37

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_testimonialclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='A unique, URL-friendly version of the title.', unique=True)),
                ('image', models.ImageField(upload_to='images/blog/', verbose_name='Blog Post Image')),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Full Blog Content')),
                ('summary', models.TextField(help_text='A brief summary for the homepage card.', max_length=300)),
                ('comment_count', models.IntegerField(default=0)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date'],
            },
        ),
    ]
