# Generated by Django 6.0 on 2025-12-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='What We Offer Section', editable=False, max_length=50, unique=True)),
                ('small_title', models.CharField(default='What We Offer?', max_length=100)),
                ('main_title', models.CharField(default='Our Company Make You Feel More Confident', max_length=255)),
                ('description_1', models.TextField(help_text='First description paragraph')),
                ('description_2', models.TextField(help_text='Second description paragraph')),
                ('feature_1', models.CharField(default='Best Sofa', max_length=100)),
                ('feature_2', models.CharField(default='Best Quality', max_length=100)),
                ('feature_3', models.CharField(default='Good Prices', max_length=100)),
                ('feature_4', models.CharField(default='Fast Delivery', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/what_we_offer/')),
            ],
            options={
                'verbose_name': 'What We Offer Section',
                'verbose_name_plural': 'What We Offer Section',
            },
        ),
        migrations.AddField(
            model_name='aboutheroimages',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/about_story/', verbose_name='Our Story Image'),
        ),
        migrations.AddField(
            model_name='aboutheroimages',
            name='story_main_title',
            field=models.CharField(default='Crafting Comfort For Every Home', max_length=255, verbose_name='Our Story Main Title (H2)'),
        ),
        migrations.AddField(
            model_name='aboutheroimages',
            name='story_paragraph_1',
            field=models.TextField(blank=True, verbose_name='Our Story Paragraph 1'),
        ),
        migrations.AddField(
            model_name='aboutheroimages',
            name='story_paragraph_2',
            field=models.TextField(blank=True, verbose_name='Our Story Paragraph 2'),
        ),
        migrations.AddField(
            model_name='aboutheroimages',
            name='story_small_title',
            field=models.CharField(default='Our Story', max_length=100, verbose_name='Our Story Small Title (H5)'),
        ),
    ]
