# Generated by Django 6.0 on 2025-12-09 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_blogcategory_blogtag_blogpost_category_blogpost_tags'),
        ('accounts', '0010_product_is_bestseller'),
    ]

    operations = [
    ]
