# Generated by Django 6.0 on 2025-12-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20251208_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetailimage',
            name='productID',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.RemoveField(
            model_name='category',
            name='categoryImage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productDate',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='productDetailDate',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='productDetailName',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductDetailImage',
        ),
    ]
